import { useLocation, Link } from "react-router-dom";
import { useEffect } from "react";
import { Brain, ArrowLeft, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";

const NotFound = () => {
  const location = useLocation();

  useEffect(() => {
    console.error(
      "404 Error: User attempted to access non-existent route:",
      location.pathname,
    );
  }, [location.pathname]);

  return (
    <div className="min-h-screen bg-background relative overflow-hidden">
      {/* Background effects matching login page */}
      <div className="absolute inset-0">
        <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-ai-glow/20 rounded-full blur-3xl animate-pulse"></div>
        <div className="absolute bottom-1/4 right-1/4 w-80 h-80 bg-human-glow/20 rounded-full blur-3xl animate-pulse delay-1000"></div>
      </div>

      <div className="relative z-10 flex items-center justify-center min-h-screen p-4 sm:p-6">
        <div className="text-center space-y-6 sm:space-y-8 max-w-xs sm:max-w-md">
          {/* Logo matching login page */}
          <div className="flex items-center justify-center space-x-2 mb-4 sm:mb-6">
            <div className="relative">
              <Brain className="w-8 h-8 sm:w-12 sm:h-12 text-ai-glow" />
              <Sparkles className="w-4 h-4 sm:w-6 sm:h-6 text-human-glow absolute -top-1 -right-1 animate-pulse" />
            </div>
            <div className="text-xl sm:text-2xl font-bold bg-gradient-to-r from-ai-glow to-human-glow bg-clip-text text-transparent">
              CanAIGuess
            </div>
          </div>

          {/* 404 Content */}
          <div className="space-y-4">
            <div className="text-6xl sm:text-8xl font-bold bg-gradient-to-r from-neural-purple to-electric-blue bg-clip-text text-transparent">
              404
            </div>
            <h1 className="text-xl sm:text-2xl font-bold">Path Not Found</h1>
            <p className="text-sm sm:text-base text-muted-foreground">
              This neural pathway doesn't exist in our reality matrix.
              <br className="hidden sm:block" />
              <span className="sm:hidden"> </span>
              Perhaps it was generated by AI?
            </p>
          </div>

          {/* Action button */}
          <Button
            asChild
            className="w-full sm:w-auto text-sm sm:text-base bg-gradient-to-r from-ai-glow to-electric-blue hover:from-ai-glow/90 hover:to-electric-blue/90 shadow-lg shadow-ai-glow/25 transition-all duration-300"
          >
            <Link to="/" className="flex items-center justify-center space-x-2">
              <ArrowLeft className="w-4 h-4" />
              <span>Return to Neural Arena</span>
            </Link>
          </Button>

          {/* Fun stats */}
          <div className="text-center text-xs sm:text-sm text-muted-foreground pt-2 sm:pt-4">
            <p>Error detected with 99.7% confidence</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default NotFound;
